source/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from project.views import ProjectListView
from to_do_list.views import MyDayView, TaskDeleteView, TaskUpdateView, PlansView

# from to_do_list.views import ToDoListView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('my_day', MyDayView.as_view(), name='my_day_view'),

    path('delete/<int:pk>', TaskDeleteView.as_view(), name='task_delete'),
    path('update/<int:pk>/', TaskUpdateView.as_view(), name='task_update'),
    path('plans/', PlansView.as_view(), name='plans_view'),

    path('accounts/', include('accounts.urls')),

    path('project/', include('project.urls'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/models.py
from django.conf import settings
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.models import Group

from to_do_list.models import Task


# from pipenv.project import Project


# Create your models here.

class ProjectRoles(models.Model):
    ROLE_CHOICES = [
        ('Manager', 'Manager'),
        ('Lead', 'Lead'),
        ('Developer', 'Developer'),
    ]

    project = models.ForeignKey('Project', on_delete=models.CASCADE, related_name='roles')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='project_roles')
    role = models.CharField(max_length=20, choices=ROLE_CHOICES)

    class Meta:
        unique_together = (('project', 'user'),)

    def __str__(self):
        return f'{self.project} | {self.user} | {self.role}'


class Project(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='project', null=True, blank=True)
    name = models.CharField(max_length=100, null=False, blank=False, verbose_name='name of the project')
    description = models.TextField(max_length=500, null=False, blank=False, verbose_name='description of the project')
    created_at = models.DateField(auto_now_add=True)
    members = models.ManyToManyField(User, related_name='projects', verbose_name='members of the project', blank=True)
    managers = models.ManyToManyField(User, related_name='managers', verbose_name='managers of the project', blank=True)
    leads = models.ManyToManyField(User, related_name='leads', verbose_name='leads of the project', blank=True)
    developers = models.ManyToManyField(User, related_name='developers', verbose_name='developers of the project', blank=True)
    # tasks = models.ForeignKey(Task, on_delete=models.CASCADE, related_name='tasks', null=True, blank=True)

    # project_groups = models.ManyToManyField(Group, related_name='projects', verbose_name='project groups', blank=True)

    def __str__(self):
        members_list = ", ".join(str(member) for member in self.members.all())
        return f'{self.name} \n Members: {members_list} \n, {self.managers}, {self.leads}, {self.developers}'

templates/partials/navigation.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light main-nav" style="background-color: #e3f2fd;">
    <h3 class="navbar-brand to-do" href="#" style="color: #666666; margin-left: 15px"><strong>To Do</strong></h3>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse nav-bar" id="navbarSupportedContent">
  <div>
  </div>
      {% include 'partials/sidebar.html' %}
          {% if not user.is_authenticated %}
              <div>
                <a href="{% url 'login' %}?next={{ request.GET.next }}" class="btn btn-outline-secondary" aria-current="page">Login</a>
                <a href="{% url 'register' %}?next={{ request.GET.next }}" class="btn btn-outline-primary" aria-current="page" style="margin-right: 100px;">Sign Up</a>
              </div>
                {% else %}
                  <div style="margin-right: 200px">
                       <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false" style="color: #ff6600; font-weight: bold;">
                                Hello, {{ request.user.username }}
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="{% url 'user_detail' %}" style="color: #ff6600; font-weight: bold;">Profile</a></li>
                                <li><a class="dropdown-item" href="{% url 'user_edit' %}" style="color: #ff6600; font-weight: bold;">Edit Profile</a></li>
                                <li><a class="dropdown-item" href="{% url 'change_password' %}" style="color: #ff6600; font-weight: bold;">Change Password</a></li>
                                <li><a class="dropdown-item" href="{% url 'logout' %}?next={{ request.GET.next }}" style="color: #ff6600; font-weight: bold;">Log-out</a></li>
                            </ul>
                        </li>

{#                      User: {{ user.username }}#}
{#                      <a href="{% url 'logout' %}?next={{ request.GET.next }}" class="btn btn-outline-danger" aria-current="page" style="margin-right: 100px;">Logout</a>#}
                  </div>
          {% endif %}

  </div>


</nav>

templates/partials/pagination.html
<div class="pagination" style="justify-content: center; margin-top: 50px">

    <span class="step-links">
        <a href="?page=1">&laquo; first</a>

        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}">prev</a>
            {% else %}
            <span class="page-disabled">prev</span>
        {% endif %}

        <form class="current-page" method="get">
            <label for="page">
                Page <input type="text" name="page" id="page" value="{{ page_obj.number }}" style="width: 40px" disabled>

                of {{ page_obj.paginator.num_pages }}.

            </label>
        </form>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            {% else %}
                <span class="page-disabled">next</span>
        {% endif %}
        <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
    </span>


</div>

templates/partials/search.html
<form class="form-inline" style="height: 45px" method="get">
        {% csrf_token %}
        <ul>
            <li class="list-group-item list-group-item-action d-flex justify-content-between main-search mt-5" style="margin-top: 3px">
                <input type="search" name="search" class="form-control" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-secondary" id="button-addon2" style="margin-left: 10px">Search</button>
            </li>
        </ul>
</form>

templates/partials/sidebar.html
{% load static %}
{% if request.user.is_authenticated %}
    <i class='bx bx-menu menu' id="toggle-menu" onclick="toggleSidebar()"></i>
{% endif %}
<div class="sidebar" id="sidebar">
    <div class="my-menu">
        <a href="{% url 'my_day_view' %}">
            <i class='bx bx-sun'></i>
            <span>My Day</span>
        </a>
    </div>

    <div class="my-menu">
        <a href="{% url 'important_list' %}">
            <i class='bx bx-star'></i>
            <span>Important</span>
        </a>
    </div>

    <div class="my-menu">
        <a href="{% url 'plans_view' %}">
            <i class='bx bx-notepad'></i>
            <span>Planned</span>
        </a>
    </div>

    <div class="my-menu">
        <a href="{% url 'project_list' %}">
            <i class='bx bx-ghost'></i>
            <span>Projects</span>
        </a>

    </div>
</div>

templates/partials/task_create.html
{% load static %}
<form action="{{ action_url }}" method="POST">
                    {% csrf_token %}
                 <div class="row p-3">
                        <div class="col col-11 mx-auto">
                             <div class="w-50">
                            {% for error in non_field_errors %}
                                <p class="form-error">{{ error }}</p>
                            {% endfor %}

                            </div>
                            <div class="row bg-white rounded shadow-sm p-2 add-todo-wrapper align-items-center justify-content-center add-task">
                                <div class="col w-50 form-add">
                                    {% if form %}
                                        <input type="text" class="form-control w-50" id = "titleInput" name = "title" placeholder="+  Add a task">

                                        <button type="button"  id="addDescription" class="btn btn-secondary" style="display: none; margin-left: 20px;">Add description</button>

                                        <button type="button" id="addPlan"  class="btn btn-outline-secondary" style="position: relative; margin-left: 10px">Connect with plan</button>

                                            <select class="form-select select-status" name="status" style="width: auto; position: relative; margin-left: 25px">
                                                    <option value="Started">Started</option>
                                                <option value="In progress">In progress</option>
                                                <option value="Done">Done</option>
                                                <option value="Forgotten">Forgotten</option>
                                            </select>
                                    {% else %}
                                     <div>
                                        <h2>We are sorry, there is some error on server</h2>
                                     </div>
                             {% endif %}

                                </div>

                                <div class="col-auto px-0 mx-0 mr-2">
                                    <button type="submit" class="btn btn-outline-success">Add</button>
                                </div>
                            </div>
                        </div>
                 </form>
                    <div class="w-100">
                        <form action="" method="GET" class="d-flex align-items-center">
                            <div style="display:flex; flex-wrap: wrap; gap: 10px; margin-left: 60px; margin-top: 20px" class="form-control w-25">
                                <div>
                                    <select name="sort_by" class="form-select form-select-sm" id="sort_by" style="height: 40px">
                                        <option value="" selected disabled>Select</option>
                                        <option value="status">Status</option>
                                        <option value="status-reverse">Status reverse</option>
                                        <option value="created_at">Date</option>
                                        <option value="title">title</option>

                                       </select>
                                </div>
                                <div>
                                    <button type="submit" class="btn btn-secondary">Sort</button>
                                </div>
                            </div>
                            {% include 'partials/search.html' %}
                        </form>
                    </div>

                            <div class="plan" id="plan" style="display: none; margin-left: 60px; margin-top: 20px; margin-bottom: 20px">
                                    <p class="mb-2">{{ form.plan.label }}</p>
                                    <select name="plan" class="form-select">
                                        {% for plan in plans %}
                                            <option value="{{ plan.pk }}">{{ plan.title }}</option>
                                        {% endfor %}
                                    </select>
                            </div>

                     <div class="description form-description" id="description" style="display: none; margin-left: 60px; margin-top: 20px">
                         {{ form.description }}
                     </div>
</div>
{#<script src="{% static 'js/main.js' %}"></script>#}

templates/partials/tasks.html
{% load static %}
{% for task in tasks %}
    <div class="row bg-white rounded shadow-sm p-2 add-todo-wrapper align-items-center justify-content-center" style="margin-top: 10px;" data-task-id="{{ task.id }}">
        <div class="col w-50 form-add" id="tasks-{{ task.id }}">
            <div class="tasks">
                <div class="form-check">
                    {% if is_manager or is_lead or is_dev or not task.project %}
                        <input class="form-check-input class-task-title" type="checkbox" value="" id="flexCheckDefault_{{ task.id }}" data-task-id="{{ task.id }}">
                    {% endif %}
                    <label class="form-check-label" for="flexCheckDefault_{{ task.id }}">
                        <div class="task-title" id="task-title-{{ task.id }}">
                            {{ task.title }}
                        </div>
                    </label>
                </div>
                <button type="button" class="btn btn-light task-description-btn font-for-all" data-task-id="{{ task.id }}" id="task-description-{{ task.id }}" style="font-weight: lighter; text-decoration: none">More info</button>
                {% if task.status == 'Started' %}
                <button type="button" class="btn btn-outline-primary" id="task-status">
                    {{ task.status }}
                </button>
            {% elif task.status == 'In progress' %}
                <button type="button" class="btn btn-outline-info" id="task-status">
                    {{ task.status }}
                </button>
            {% elif task.status == 'Done' %}
                <button type="button" class="btn btn-outline-success" id="task-status" >
                    {{ task.status }}
                </button>
            {% elif task.status == 'Forgotten' %}
                <button type="button" class="btn btn-outline-danger" id="task-status">
                    {{ task.status }}
                </button>
            {% elif not task.status %}
                <button type="button" class="btn btn-outline" id="task-status">
                    No status
                </button>
            {% endif %}

                {% if is_manager or is_dev or is_lead or not task.project %}
                    <a href="{% url 'task_delete' task.pk %}" class="delete-task-btn" data-task-id="{{ task.id }}" style="margin-left: 0; position: relative">
                        <i class='bx bx-trash' id="icons-trash"></i>
                    </a>
                    <a href="{% url 'important' task.id %}">
                        {% if task.check_important %}
                            <i class='bx bxs-star' id="icons" style='color:#e8d667'></i>
                        {% else %}
                            <i class='bx bx-star' id="icons"></i>
                        {% endif %}
                    </a>
                {% endif %}
            </div>
        </div>
    </div>

    <div class="form-control w-50 font-for-all" id="task-description--{{ task.id }}" style="display: none; margin-left: 60px; margin-top: 5px; font-weight: lighter; text-decoration: none; justify-content: space-between">
        {{ form.description.label }}
        <p class="text-success">{{ task.description|default:"Empty" }}</p>
        {% if is_manager or is_dev or is_lead or not task.project %}
            <div id="task-update-container-{{ task.id }}" style="display: block">
                {% include 'task_update.html' %}
            </div>
        {% endif %}
    </div>
{% endfor %}
</div>
<script src="{% static 'js/main.js' %}"></script>

templates/partials/user_forms.html
{% if not fields_only %}
    <form action="{{ action_url }}" method="{{ form_method }}" enctype="multipart/form-data">
    {% csrf_token %}
{% endif %}

    {% for errors in form.non_field_errors %}
        <p class="text-danger">{{ errors }}</p>
    {% endfor %}

    {% for field in form %}
        <div class="form-group">
            <div class="input-group mb-3">
                <span class="input-group-text">{{ field.label }}</span>
                {{ field }}
            </div>
        </div>

        {% for errors in field.errors %}
            <p class="text-danger">{{ errors }}</p>
        {% endfor %}

    {% endfor %}

{% if not fields_only %}
    <button type="submit" class="btn btn-outline-success">{{ button_text|default:"Submit" }}</button>
    </form>
{% endif %}