accounts/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from accounts.views import login_view, logout_view, register_view, RegistrationView, important_view, \
    important_list_view, UserDetailView, UserUpdateView, PasswordChangeView
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', register_view, name='register'),
    path('important/<int:id>', important_view, name='important'),
    path('user/important/', important_list_view, name='important_list'),
    path('profile/', UserDetailView.as_view(), name='user_detail'),
    path('profile/edit/', UserUpdateView.as_view(), name='user_edit'),
    path('profile/change_password/', PasswordChangeView.as_view(), name='change_password')
    # path('login', LoginView.as_view(), name='login'),
    # path('logout', LogoutView.as_view(), name='logout'),
]

source/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from project.views import ProjectListView
from to_do_list.views import MyDayView, TaskDeleteView, TaskUpdateView, PlansView

# from to_do_list.views import ToDoListView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('my_day', MyDayView.as_view(), name='my_day_view'),

    path('delete/<int:pk>', TaskDeleteView.as_view(), name='task_delete'),
    path('update/<int:pk>/', TaskUpdateView.as_view(), name='task_update'),
    path('plans/', PlansView.as_view(), name='plans_view'),

    path('accounts/', include('accounts.urls')),

    path('project/', include('project.urls'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth import get_user_model


# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(get_user_model(), on_delete=models.CASCADE, related_name='profile',
                                verbose_name='profile')
    position = models.CharField(max_length=100, verbose_name='position', null=True, blank=True)
    number = models.CharField(max_length=20, verbose_name='number', null=True, blank=True)
    birth_date = models.DateField(verbose_name='birth date', null=True, blank=True)
    avatar = models.ImageField(upload_to='user_pics', verbose_name='avatar', null=True, blank=True)

    def __str__(self):
        return self.user.get_full_name()

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UsernameField
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
from accounts.models import Profile


class RegistrationForm(forms.ModelForm):
    password = forms.CharField(
        label='Password',
        required=True,
        strip=False,
        widget=forms.PasswordInput()
    )

    password_confirm = forms.CharField(
        label='Password Confirm',
        required=True,
        strip=False,
        widget=forms.PasswordInput()
    )

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        password_confirm = cleaned_data.get('password_confirm')

        if password and password_confirm and password != password_confirm:
            raise forms.ValidationError('Passwords do not match!')

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()
        return user

    class Meta:
        model = User
        fields = ['username', 'password', 'password_confirm', 'first_name', 'last_name', 'email']


# class RegistrationForm(UserCreationForm):
#     class Meta(UserCreationForm.Meta):
#         fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']

class UserEditForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ['first_name', 'last_name', 'email']
        labels = {'first_name': 'First Name', 'last_name': 'Last Name', 'email': 'Email'}

        widgets = {'username': forms.TextInput(attrs={'class': 'form-control w-50'}),
                   'first_name': forms.TextInput(attrs={'class': 'form-control w-50'}),
                   'last_name': forms.TextInput(attrs={'class': 'form-control w-50'}),
                   'email': forms.EmailInput(attrs={'class': 'form-control w-50'}),}


class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['position', 'number', 'birth_date', 'avatar']
        labels = {'position': 'Position', 'number': 'Number', 'birth_date': 'Birth Date', 'avatar': 'Avatar'}

        widgets = {'position': forms.TextInput(attrs={'class': 'form-control w-50'}),
                   'number': forms.TextInput(attrs={'class': 'form-control w-50'}),
                   'birth_date': forms.DateInput(attrs={'class': 'form-control w-50', 'type' : 'date'}),
                   'avatar': forms.FileInput(attrs={'class': 'form-control w-50'})}


class PasswordChangeForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}), label='Password', strip=False)
    password_confirm = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}), label='Password Confirm', strip=False)
    old_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}), label='Old password', strip=False)

    def clean_password_confirm(self):
        password = self.cleaned_data.get("password")
        password_confirm = self.cleaned_data.get("password_confirm")

        if password and password_confirm and password != password_confirm:
            raise forms.ValidationError("Password don't match")

        return password_confirm

    def clean_old_password(self):
        old_password = self.cleaned_data.get("old_password")

        if not self.instance.check_password(old_password):
            raise forms.ValidationError("Old password is incorrect")

        return old_password

    def save(self, commit=True):
        user = self.instance
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

    class Meta:
        model = get_user_model()
        fields = ('old_password', 'password', 'password_confirm')

accounts/views.py
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import reverse
from django.views.generic import CreateView, DetailView, UpdateView
from django.contrib.auth.models import User

from accounts.forms import RegistrationForm, UserEditForm, ProfileEditForm, PasswordChangeForm
from accounts.models import Profile
from to_do_list.models import Task


# Create your views here.


def login_view(request):
    context = {}
    print(request.GET)
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user:
            login(request, user)
            next = request.GET.get('next')
            if next:
                return redirect(next)
            else:
                print('no next')
            return redirect('my_day_view')
        else:
            context['has_error'] = True
    return render(request, 'accounts/login.html', context)


@login_required
def logout_view(request):
    logout(request)
    next = request.GET.get('next')
    if next:
        return redirect(next)
    return redirect('home')


def register_view(request):
    if request.user.is_authenticated:
        return redirect('my_day_view')
    if request.method == 'POST':
        form = RegistrationForm(data=request.POST)
        if form.is_valid():
            user = form.save()
            Profile.objects.create(user=user)
            login(request, user)
            return redirect('my_day_view')
    else:
        form = RegistrationForm()
    return render(request, 'accounts/register.html', context={'form': form})


class RegistrationView(CreateView):
    model = User
    template_name = 'accounts/register.html'
    form_class = RegistrationForm

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect(self.get_success_url())

    def get_success_url(self):
        next = self.request.GET.get('next')
        if not next:
            next = self.request.POST.get('get')
        return next


@login_required
def important_view(request, id):
    task = get_object_or_404(Task, id=id)
    if task.important.filter(id=request.user.id).exists():
        task.important.remove(request.user)
        task.check_important = False
    else:
        task.important.add(request.user)
        task.check_important = True
    task.save()
    return redirect('important_list')


def important_list_view(request):
    important_list = Task.objects.filter(important=request.user)
    return render(request, 'my_important.html', {'important_list': important_list})


class UserDetailView(DetailView):
    model = get_user_model()
    template_name = 'accounts/detail_view.html'
    context_object_name = 'user_object'

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        return context

    def get_object(self, queryset=None):
        return self.request.user


class UserUpdateView(LoginRequiredMixin, UpdateView):
    model = get_user_model()
    template_name = 'accounts/edit.html'
    context_object_name = 'user_object'
    form_class = UserEditForm

    def get_context_data(self, **kwargs):
        if 'profile_form' not in kwargs:
            kwargs['profile_form'] = self.get_profile_form()
            # print(kwargs)
        return super().get_context_data(**kwargs)

    def get_profile_form(self):
        profile_form = {'instance': self.object.profile}
        if self.request.method == 'POST':
            profile_form['data'] = self.request.POST
            profile_form['files'] = self.request.FILES
        return ProfileEditForm(**profile_form)

    def get_success_url(self):
        return reverse('user_detail')

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        profile_form = self.get_profile_form()

        if form.is_valid() and profile_form.is_valid():
            return self.form_valid(form, profile_form)
        else:
            return self.form_invalid(form, profile_form)

    def form_valid(self, form, profile_form):
        response = super().form_valid(form)
        profile_form.save()
        return response

    def form_invalid(self, form, profile_form):
        context = self.get_context_data(form=form, profile_form=profile_form)
        return render(context)

    def get_object(self, queryset=None):
        return self.request.user


class PasswordChangeView(LoginRequiredMixin, UpdateView):
    model = get_user_model()
    form_class = PasswordChangeForm
    template_name = 'accounts/change_password.html'
    context_object_name = 'user_object'

    def get_object(self, queryset=None):
        return self.request.user

    def get_success_url(self):
        return reverse('login')

templates/accounts/change_password.html
{% extends 'base.html' %}

{% block content %}
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <h1 class="card-title">Change Password</h1>
                    {% include 'partials/user_forms.html' with form_method='POST' %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/accounts/detail_view.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">
                        <h1 class="card-title">{{ user_object.username }}'s Profile</h1>
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-4">
                                {% if user_object.profile.avatar %}
                                    <img src="{{ user_object.profile.avatar.url }}" class="img-fluid" alt="avatar">
                                        {% else %}
                                            <img src="{% static 'img/Untitled.jpeg' %}" alt="default">
                                {% endif %}
                            </div>
                            <div class="col-md-8">
                                <ul class="list-group">
                                    <li class="list-group-item"><strong>Username:</strong>{% if user_object.username %} {{ user_object.username }} {% else %} <p class="text-warning">Not declared</p> {% endif %}</li>
                                    <li class="list-group-item"><strong>First Name:</strong> {% if user_object.first_name %} {{ user_object.first_name }} {% else %} <p class="text-warning">Not declared</p>  {% endif %}</li>
                                    <li class="list-group-item"><strong>Last Name:</strong>{% if user_object.last_name %} {{ user_object.last_name}} {% else %} <p class="text-warning">Not declared</p>  {% endif %}</li>
                                    <li class="list-group-item"><strong>Birth Date:</strong> {% if user_object.profile.birth_date %} {{ user_object.profile.birth_date }} {% else %}<p class="text-warning">Not declared</p>  {% endif %}</li>
                                    <li class="list-group-item"><strong>Position:</strong>{% if user_object.profile.position %} {{ user_object.profile.position }} {% else %} <p class="text-warning">Not declared</p> {% endif %}</li>
                                    <li class="list-group-item"><strong>Number:</strong> {% if user_object.profile.number %} {{ user_object.profile.number  }} {% else %} <p class="text-warning">Not declared</p>  {% endif %}</li>
                                </ul>

                                <div class="text-end">
                                    <a href="{% url 'user_edit' %}" class="btn btn-outline-secondary m-3">Edit profile</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/accounts/edit.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-body">
                    <form action="{% url 'user_edit' %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'partials/user_forms.html' with form=form fields_only=True %}
                        {% include 'partials/user_forms.html' with form=profile_form fields_only=True %}
                        <button type="submit" class="btn btn-outline-success mt-3">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}

    <div class="container">
        <div class="row justify-content-center mt-5">
            <div class="col-md-6">
                <h1 class="text-center">Login</h1>
                <form action="{% url 'login' %}?next={{ request.GET.next }}" method="post" class="form-control">
                    {% csrf_token %}
                    {% if has_error %}
                        <p style="color: red">Invalid username or password!</p>
                    {% endif %}
                    <div class="mb-3">
                        <label for="username" class="form-label">Username</label>
                        <input type="text" name="username" id="username" class="form-control">
                    </div>

                    <div class="mb-3">
                        <label for="password" class="form-label">Password</label>
                        <input type="password" name="password" id="password" class="form-control">
                    </div>

                    <button type="submit" class="btn btn-outline-success btn-block mt-3">Login</button>
                    <a href="{% url 'register' %}" class="btn btn-outline-primary btn-block mt-3">Register</a>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/accounts/register.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="row justify-content-center mt-5">
        <h1 class="text-center">Registration</h1>
        <div class="col-md-6">
            <div class="card shadow-lg">
                <div class="card-body">
                    <form action="{% url 'register' %}?next={{ request.GET.next }}" method="post">
                        {% csrf_token %}
                        {% for error in form.non_field_errors %}
                            <p class="alert alert-danger">{{ error }}</p>
                        {% endfor %}

                        {% for error in form.errors %}
                                <p class="text-danger">{{ error }}</p>
                        {% endfor %}

                        <div class="form-group mb-3">
                            <label for="id_username">Username:</label>
                            <input type="text" name="username" id="username" class="form-control">
{#                            {{ form.username }}#}
                        </div>

                        <div class="form-group mb-3">
                            <label for="id_password">Password:</label>
                            <input type="password" name="password" id="password" class="form-control">
{#                            {{ form.password }}#}
                        </div>

                        <div class="form-group mb-3">
                            <label for="id_password_confirm">Password Confirm:</label>
                            <input type="password" name="password_confirm" id="password_confirm" class="form-control">
{#                            {{ form.password_confirm }}#}
                        </div>

                        <div class="form-group mb-3">
                            <label for="id_first_name">First Name:</label>
                            <input type="text" name="first_name" id="first_name" class="form-control">
{#                            {{ form.first_name }}#}
                        </div>

                        <div class="form-group mb-3">
                            <label for="id_last_name">Last Name:</label>
                            <input type="text" name="last_name" id="last_name" class="form-control">
{#                            {{ form.last_name }}#}
                        </div>

                        <div class="form-group mb-3">
                            <label for="id_email">Email:</label>
                            <input type="text" name="email" id="email" class="form-control">
{#                            {{ form.email }}#}
                        </div>

                        <button type="submit" class="btn btn-outline-success btn-block mt-4">Register</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}